---

- hosts: routers
  gather_facts: no
  connection: network_cli
  become_method: enable

  tasks:
    - name: Configure local AAA authentication for console access
      ios_config:
        commands:
          - aaa new-model
          - aaa authentication login default local

    - name: Configure the line console to use the defined AAA authentication method
      ios_config:
        commands:
          - login authentication default
        parents: line console 0

    - name: Configure a named list AAA authentication method for the vty lines
      ios_config:
        commands:
          - aaa authentication login SSH-LOGIN local

    - name: Configure the vty lines to use the defined AAA authentication method
      ios_config:
        commands:
          - login authentication SSH-LOGIN
        parents: line vty 0 4